image: bayesimpact/react-base:latest

before_script:
  - npm install -g webpack
  - npm install

production:
  only: 
    - prod
  script:
    - npm run production

    # Remote index.html from ./dist because it's being rendered instead of /views/index.html for server side-rendering (2017-08-28)
    - rm -rf ./dist/index.html

    # Install ssh-agent if not already installed, it is required by Docker.
    # (change apt-get to yum if you use a CentOS-based image)
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'

    # Setup SSH
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_AWS_KEY")
    - mkdir -p ~/.ssh
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config

    # Install rsync
    - apt-get update && apt-get upgrade -y && apt-get dist-upgrade -y && apt-get -y install rsync && apt-get -y install sshpass

    # Sync
    - echo $SSH_AWS_KEY > univjobs-dmz-server.pem
    - rsync -avL --inplace --rsync-path='/usr/bin/sudo /usr/bin/rsync' --progress -e "ssh -i univjobs-dmz-server.pem" ./dist ubuntu@52.60.179.192:/home/ubuntu/univjobs/univjobs-front



