// These are the main pages that we use to route to
export AboutPageContainer from './AboutPage/containers/AboutPageContainer'
// export ApplicationsContainer from './Applications/containers/ApplicationsContainer'
export ApplicantsContainer from './Applications/containers/ApplicantsContainer'
// export ApplicationModal from './SharedComponents'
export CategoriesContainer from './Categories/containers/CategoriesContainer'
export ContactPageContainer from './ContactPage/containers/ContactPageContainer'
export CreateJobContainer from './CreateJob/containers/CreateJobContainer'
export EmployerProfileContainer from './Profile/containers/EmployerProfileContainer'
export EmployerDashboardContainer from './Dashboard/containers/EmployerDashboardContainer'
export InitialOverlay from './Main/containers/InitialOverlay'
export MyPostingsContainer from './MyPostings/containers/MyPostingsContainer'
export StudentSettingsContainer from './Settings/containers/StudentSettingsContainer'
export SignupContainer from './SignupAndLogin/containers/SignupContainer'
export StudentProfileContainer from './Profile/containers/StudentProfileContainer'
export StudentDashboardContainer from './Dashboard/containers/StudentDashboardContainer'
export Terms from './Legal/components/Terms'
export PinJobsContainer from './PinJobs/containers/PinJobsContainer'
export Privacy from './Legal/components/Privacy'
export GenericCard, { APPLICATIONS_CARD_TYPE, DASHBOARD_CARD_TYPE, PINNED_JOBS_CARD_TYPE } from './SharedComponents'
export PasswordResetContainer from './PasswordReset/containers/PasswordResetContainer'
export PageNotFoundContainer from './PageNotFound/containers/PageNotFoundContainer'
export PublicJobViewContainer from './PublicJobView/containers/PublicJobViewContainer'
export MyApplicantsContainer from './MyApplicants/containers/MyApplicantsContainer'